### ISSUE TITLE
When will the code be realeased?

### ISSUE THREAD

**Issue by hongge831** [FightingFighting/GPS#1]
When will the code be realeased?

**Comment by FightingFighting** [comment]
we will release it soon.  I hope it can be made this weekend.

**Comment by hiyyg** [comment]
> we will release it soon. I hope it can be made this weekend.

delayed?

**Comment by FightingFighting** [comment]
> > we will release it soon. I hope it can be made this weekend.
> 
> delayed?

Sorry, we kind of busy. we will release it this week.

**Comment by FightingFighting** [comment]
> > > we will release it soon. I hope it can be made this weekend.
> > 
> > 
> > delayed?
> 
> Sorry, we kind of busy. we will release it this week.

i mean next week.

**Comment by xben-cherry** [comment]
delayed？

**Comment by FightingFighting** [comment]
@xben-cherry Sorry, I promise the code will be released this week.
