### ISSUE TITLE
Code fine-tuned by sam

### ISSUE THREAD

**Issue by XUYU0205** [FightingFighting/GPS#3]
Hello, could you please provide the code for fine-tuning the sam segmentation of polyps? If so, I would be very grateful.

**Comment by FightingFighting** [comment]
Thank you for your interesting in our work. I will release the code shortly.

**Comment by FightingFighting** [comment]
Thank you for your interest in our work. I will release the code shortly.

**Comment by XUYU0205** [comment]
Please tell me when will it be released?

**Comment by FightingFighting** [comment]
@XUYU0205 we will release it this Tuesday

**Comment by xjiangmed** [comment]
@FightingFighting Thanks for the update. Could you provide the code for utils.calc_mDics_and_mIou in SAM.test.py？

**Comment by FightingFighting** [comment]
@xjiangmed we did not implement it.  Instead, we use "from models.mmseg.core.evaluation.metrics import eval_metrics".

**Comment by xjiangmed** [comment]
Thanks a lot for your help
