### ISSUE TITLE
Missing Files for CIFAR-100 Reproduction

### ISSUE THREAD

**Issue by kennethyangg** [FightingFighting/GPS#7]
Hi,

Thank you for the great work! I'm trying to reproduce the results for CIFAR-100. However, I found that I am unable to download from OneDrive since parts 3 and 5 are being converted into zip files and cannot be unzipped. Therefore, I decided to download from the original VTAB repository, but I couldn't find the two text files provided in your code, train800val200.txt and test.txt.

Do you have any suggestions regarding this? I appreciate your help!

Best regards,
Kenneth

**Comment by FightingFighting** [comment]
maybe download it from Baiduyun?  The file there has train800val200.txt and test.txt.

**Comment by kennethyangg** [comment]
@FightingFighting Thanks for the reply. I actually tried to download it from Baiduyun. For parts 1 and 5, due to the file size, it became a zip file, and I'm unable to unzip it. Do you have any comments on this? I appreciate your help!
![issue](https://github.com/user-attachments/assets/bfedb80e-b519-46fe-a5e2-77922ab4915b)

**Comment by FightingFighting** [comment]
Hi, maybe this is caused by the system. I just try to download in the windows. It was not splited and normally unzip. In the case, maybe you could try to download them in your windows or fo the SSF repo to get these files.

**Comment by FightingFighting** [comment]
I just upload all annotations here, please download it from [vtab-1k_anno.zip](https://github.com/user-attachments/files/17435375/vtab-1k_anno.zip).

**Comment by kennethyangg** [comment]
Hi @FightingFighting , sorry to bother you. After downloading the files from Baiduyun, I received vtab-1k.tar.gz.part1 to vtab-1k.tar.gz.part5. Could you please guide me on what to do next? I tried concatenating them into vtab-1k.tar.gz, but I was unable to extract it because the file format seems unusual (it appears to contain both .tar and .gz in an unexpected way).
![image](https://github.com/user-attachments/assets/a910966c-1044-43b6-96a3-d270bf3bd8f7)

**Comment by FightingFighting** [comment]
Hi @CSYangHsu , I am not very sure this problem as I cannot reproduce the problem. but you could try this: 
![image](https://github.com/user-attachments/assets/7f61e88d-d42d-4aae-b339-b4a1439d54e4)

**Comment by kennethyangg** [comment]
Hi @FightingFighting , thanks for the reply! I still have issue downloading from Baiduyun. Do you mind uploading it to Google drive or Onedrive?

**Comment by FightingFighting** [comment]
Hi @CSYangHsu yes, you can download from [here](https://drive.google.com/file/d/14dTPCoWOQ_4vcPYFvjXpAvBcoqtInEZz/view?usp=sharing).

**Comment by kennethyangg** [comment]
Hi @FightingFighting  ,thank you so much! I really appreciate your help. 🙏
Would you mind uploading FGVC dataset to Google Drive as well? That would be incredibly helpful. Thanks again! 😊

**Comment by FightingFighting** [comment]
Hi @CSYangHsu, download from [here](https://drive.google.com/drive/folders/110TEuKscYJdsb3EbddzBsInotxyMnLKB?usp=sharing)

**Comment by kennethyangg** [comment]
@FightingFighting, thank you so much!
