### ISSUE TITLE
Dataset split files, e.g., train.json, no longer available 

### ISSUE THREAD

**Issue by uqzhichen** [FightingFighting/GPS#8]
Hi Zhi and Qizhe, the dataset split files provided in VPT github repo no longer available. Would you like to provide a google drive link for them?

Best

**Comment by FightingFighting** [comment]
Hi @uqzhichen, I just update the readme. you could download following the instruction.

**Comment by uqzhichen** [comment]
> Hi @uqzhichen, I just update the readme. you could download following the instruction.

Much appreciated.
