### ISSUE TITLE
Request for code usage permission

### ISSUE THREAD

**Issue by Jwonno** [FightingFighting/GPS#9]
Thank you for sharinng the code for your paper. 

It's incredibly helpful and insightful, but i noticed that the repository doesn't have a lincense specified. 
Would it be possible to clarify if I can use the code for a personal, non-commercial project?

**Comment by FightingFighting** [comment]
Hi, thank you for your interest in our project. I already added MIT License to the project. You can use the code for a personal, non-commercial project.

**Comment by Jwonno** [comment]
Thank you, I really appreciate it!
